// apps/test-analytics/src/app/app.component.ts
import { Component, ViewEncapsulation, Inject, OnInit, Optional, inject, DestroyRef, ChangeDetectorRef } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { CommonModule } from '@angular/common';
import { subscribeToGlobalEvents } from '@shared/logic';
import { type GlobalEvent } from '@shared/types' 

@Component({
  selector: 'app-root',
  standalone: true,
  encapsulation: ViewEncapsulation.None,
  imports: [CommonModule, RouterOutlet],
  template: `
    <h2 class="bg-slate-500 p-4 text-2xl font-black uppercase text-white">
      TEST TAILWINDA w angular 19
    </h2>
    
    <div [class.dark]="theme === 'dark'" 
        class="p-4 border border-slate-300 transition-colors duration-300
                dark:bg-slate-900 dark:border-slate-700 dark:text-white">
      
      <h2 class="mb-8 text-xl font-bold dark:text-blue-400">
        Angular Analytics Module
      </h2>
      
      <p class="mb-4 text-slate-600 dark:text-slate-400">
        Aktualny motyw: <strong class="text-black dark:text-white">{{ theme }}</strong>
      </p>
      
      <p class="mb-0 text-slate-600 dark:text-slate-400">
        Propsy z test-dashboard: 
      </p>
      <pre class="mb-4 text-xs text-indigo-600 dark:text-indigo-200 font-mono">{{ user | json }}</pre>

      <div class="p-4 rounded bg-slate-100 dark:bg-slate-800">
        <router-outlet></router-outlet>
      </div>
    </div>`,
})
export class AppComponent implements OnInit {
  private destroyRef = inject(DestroyRef);
  private cdr = inject(ChangeDetectorRef);
  theme: string = 'light';
  user: any = {};

  constructor(@Optional() @Inject('MICRO_PROPS') private props: any) {}

  ngOnInit() {
    if (this.props) {
      this.theme = this.props.theme || 'light';
      this.user = this.props.user || {};
    }

    const unsubscribe = subscribeToGlobalEvents(
      (event: GlobalEvent<string>) => {
        this.theme = event.payload;
        this.cdr.detectChanges();
      },
      { type: 'ui:theme-change' } 
    );

    this.destroyRef.onDestroy(() => unsubscribe());
  }
}

// apps/test-task-manager/src/App.tsx
import React, { useEffect, useState } from 'react';
import { TM_MicroAppProps } from '@shared/types';
import { useLogger } from './providers/LoggerProvider';
// import { subscribeToGlobalEvents } from '@shared/logic';
import { emitTaskEvent, useGlobalEvent } from './helpers/events';

const App = ({
  standalone = false,
  theme: initialTheme,
  user,
}: TM_MicroAppProps) => {
  const logger = useLogger();
  const [currentTheme, setCurrentTheme] = useState(initialTheme);

  useGlobalEvent('ui:theme-change', (theme) => {
    logger.info('Event', `Zmieniam motyw na: ${theme}`);
    setCurrentTheme(theme);
  });

  /* useEffect(() => {
    const unsubscribe = subscribeToGlobalEvents(
      (event) => {
        logger.info('Event', `Zmieniam motyw na: ${event.payload}`);
        setCurrentTheme(event.payload);
      },
      { type: 'ui:theme-change' }
      // { type: /^ui:theme-change/ }
    );
    return unsubscribe;
  }, []); */
  
  const handleCreateTask = () => {
    emitTaskEvent('tasks:created', { title: 'Nowe zadanie' });
    /* emitGlobal('task-manager', 'tasks:created', {
      title: 'Nowe zadanie'
    }) */
  }

  const handleDeleteTask = () => {
    emitTaskEvent('tasks:deleted', { id: 1234 });
  }

  return (
    <div className={`p-4 transition-colors duration-300 dark:bg-slate-900 dark:text-white bg-white text-slate-900`}>

      <h2 className="text-xl font-bold">
        <span className="text-2xl">🚀</span>
        {' '}Task Manager{' '}
        <span className="text-cyan-400">Micro-frontend</span>
      </h2>

      <p className="text-slate-400 mb-6">
        Jestem komponentem napisanym w <strong className={`transition-colors duration-300 text-black dark:text-slate-200`}>React</strong>, 
        działającym wewnątrz dashboardu.
      </p>

      {standalone && (
        <div className="inline-block px-3 py-1 mb-6 text-xs font-medium bg-amber-500/10 text-amber-500 border border-amber-500/20 rounded-full">
          Mode: Standalone
        </div>
      )}

      <p>Aktualny motyw: <span className="font-mono">{currentTheme}</span></p>
      
      <div className="mb-4 flex items-center gap-4">
        <button 
          onClick={handleCreateTask}
          className="mt-4 px-4 py-2 bg-blue-600 text-white rounded shadow cursor-pointer"
        >
          Dodaj zadanie
        </button>

        <button 
          onClick={handleDeleteTask}
          className="mt-4 px-4 py-2 bg-blue-600 text-white rounded shadow cursor-pointer"
        >
          Usuń zadanie
        </button>
      </div>

      <p className="mb-0 text-slate-600 dark:text-slate-400">
        Propsy z test-dashboard: 
      </p>
      <pre className="mb-4 text-xs text-indigo-600 dark:text-indigo-200 font-mono">{JSON.stringify(user, null, 2)}</pre>

    </div>
  );
};

export default App;
